// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iezvboczfhysobiszbfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllenZib2N6Zmh5c29iaXN6YmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDc3MzgsImV4cCI6MjA3NDA4MzczOH0.XA8fNEzBx2atK2K2uvjD0S-ZVEkJFij9o28o4n-cNSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});